ui_icons.icon_pack_options.ui_icons_iconify_flags:
  type: ui_icons.ui_icons_iconify_default

ui_icons.icon_pack_options.ui_icons_iconify_circle_flags:
  type: ui_icons.ui_icons_iconify_default

ui_icons.icon_pack_options.ui_icons_iconify_geo:
  type: ui_icons.ui_icons_iconify_default

ui_icons.icon_pack_options.ui_icons_iconify_animated:
  type: ui_icons.ui_icons_iconify_default

ui_icons.icon_pack_options.ui_icons_iconify_emoji:
  type: ui_icons.ui_icons_iconify_default

ui_icons.icon_pack_options.ui_icons_iconify_programming:
  type: ui_icons.ui_icons_iconify_default

ui_icons.ui_icons_iconify_default:
  type: mapping
  label: 'Iconify settings'
  constraints:
    FullyValidatable: ~
  mapping:
    width:
      type: integer
      label: 'Width'
      constraints:
        Range:
          min: 0
    height:
      type: integer
      label: 'Height'
      constraints:
        Range:
          min: 0
    flip:
      label: 'Flip'
      type: string
      constraints:
        NotBlank: []
    rotate:
      label: 'Rotate'
      type: string
      constraints:
        NotBlank: []
