variables:
  _CSPELL_IGNORE_PATHS: 'modules/ui_icons_ckeditor5/js/build/icon.js, modules/ui_icons_example/assets/**/*.json, **/*.svg'
  _CSPELL_WORDS: 'corge, Iconset, iconset, mogtofu, Valverde, svgs'

include:
  - project: $_GITLAB_TEMPLATES_REPO
    ref: $_GITLAB_TEMPLATES_REF
    file:
      - "/includes/include.drupalci.main.yml"
      - "/includes/include.drupalci.variables.yml"
      - "/includes/include.drupalci.workflows.yml"
