site_name: UI Icons for Drupal
site_author: Jean Valverde
site_description: >-
  UI Icons module documentation to provide generic Icon packs integration for
  Drupal.

repo_name: project/ui_icons
repo_url: https://git.drupalcode.org/project/ui_icons

theme:
  name: material
  language: en
  palette:
    primary: blue

extra:
  social:
    - icon: fontawesome/brands/drupal
      link: https://www.drupal.org/project/ui_icons
    - icon: fontawesome/brands/gitlab
      link: https://git.drupalcode.org/project/ui_icons
    - icon: fontawesome/solid/blog
      link: https://developpeur-drupal.com/en

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      linenums: true
      guess_lang: false
  - markdown.extensions.footnotes
  - pymdownx.extra

nav:
  - Documentation: 'docs/index.md'
  - Drupal.org project: 'https://www.drupal.org/project/ui_icons'
