ui_icons.icon_pack_options.*:
  type: ui_icons.icon_pack_options_default
  label: 'Default settings'
  constraints:
    FullyValidatable: ~

ui_icons.icon_pack_options_default:
  type: mapping
  label: 'Default settings'
  constraints:
    FullyValidatable: ~
  mapping:
    width:
      type: integer
      label: 'Width'
      constraints:
        Range:
          min: 0
    height:
      type: integer
      label: 'Height'
      constraints:
        Range:
          min: 0
    title:
      type: label
      label: 'Title'
    alt:
      type: label
      label: 'Alternative text'
