ui_icons.icon_pack_options_default:
  type: mapping
  label: 'Default settings'
  mapping:
    width:
      type: integer
      label: 'Width'
    height:
      type: integer
      label: 'Height'
    title:
      type: label
      label: 'Title'
    alt:
      type: label
      label: 'Alternative text'
