field.formatter.settings.ui_icon_link_formatter:
  type: mapping
  label: 'UI icon formatter link settings'
  mapping:
    icon_settings:
      type: sequence
      label: 'Icon extractor settings'
      # sequence:
      #   type: sequence
      #   sequence:
      #     type: string
    icon_display:
      type: string
      label: 'Icon display position'
    # @see web/core/modules/link/config/schema/link.schema.yml
    trim_length:
      type: integer
      label: 'Trim link text length'
    url_only:
      type: boolean
      label: 'URL only'
    url_plain:
      type: boolean
      label: 'Show URL as plain text'
    rel:
      type: string
      label: 'Add rel="nofollow" to links'
    target:
      type: string
      label: 'Open link in new window'

field.widget.settings.ui_icon_link_widget:
  type: mapping
  label: 'UI icon widget link settings'
  mapping:
    allowed_iconset:
      type: sequence
      label: 'Iconset limitation for selection'
      sequence:
        type: string
        label: 'Iconset id'
    show_settings:
      type: boolean
      label: 'Show extractor settings'
    icon_required:
      type: boolean
      label: 'Set icon required'
    icon_position:
      type: boolean
      label: 'Allow iconset display selection'
    # @see web/core/modules/link/config/schema/link.schema.yml
    placeholder_url:
      type: string
      label: 'Placeholder for URL'
    placeholder_title:
      type: label
      label: 'Placeholder for link text'
